UI and sounds
FeatheredElephant/DC_Jam_2024 pull request #14
Opened 2024-03-27 21:37 UTC by apotter3

Main Menu basically has everything it needs.
- Volume settings for music and effects
- A credits and controls page

2024-03-27 21:37 UTC, apotter3 commented
let me know whatcha think

2024-03-27 23:37 UTC, FeatheredElephant requested changes
Please remove fluff from 3p assets (sample scenes, unused assets, etc.)

2024-03-28 18:27 UTC, apotter3 commented
-Deleted
- Unused TMP files
- Unused sounds

Left some sounds I think would be good for some effects going forward (Slashing, enemy sounds)

Sample scenes have been removed in most recent commits

2024-03-29 23:20 UTC, FeatheredElephant approved these changes

2024-03-29 23:20 UTC, merged